### ISSUE TITLE
Issue with http-proxy: socket hang up

### ISSUE THREAD

**Issue by kud** [jaywcjlove/mocker-api#112]
Hello! And first of all, thanks for your project, it's really efficient!

My issue is that sometimes (mostly when I run cypress on the proxy), I've got this:

```
/node_modules/http-proxy/lib/http-proxy/index.js:120
    throw err;
    ^

Error: socket hang up
    at connResetException (internal/errors.js:614:14)
    at TLSSocket.socketCloseListener (_http_client.js:441:25)
    at TLSSocket.emit (events.js:327:22)
    at net.js:670:12
    at TCP.done (_tls_wrap.js:562:7) {
  code: 'ECONNRESET'
}
npm ERR! code ELIFECYCLE
```

Do you have any idea why?

Running cypress too many times on it is too much for the proxy?

**Comment by jaywcjlove** [comment]
@kud Any examples for me?

**Comment by kud** [comment]
I close this issue as I use now msw.js. I won't be able to have a try again.
Thank you for your time. :)
