### ISSUE TITLE
d.ts有个小错误

### ISSUE THREAD

**Issue by gapkukb** [jaywcjlove/mocker-api#117]
![image](https://user-images.githubusercontent.com/15757875/88241656-4f53d200-ccbd-11ea-8cba-dd5ff20d6bd9.png)
![image](https://user-images.githubusercontent.com/15757875/88242293-5aa7fd00-ccbf-11ea-8a83-abcfbda71f99.png)

MockerOption.proxy 应该是{[key:string]:string}或者Record<string,string>. 多了双引号变成字符串了

**Comment by jaywcjlove** [comment]
@gapkukb `Upgrade mocker-api@2.1.1`
