### ISSUE TITLE
之前一直在用2.0.4版，之前配置了proxy, 如果有配置mocker的路径就走mock,没有就走代理的特性没有了

### ISSUE THREAD

**Issue by aizigao** [jaywcjlove/mocker-api#151]
这个特性，是我用这个项目的主要原因，我升了个级后这个特性没有了，我也就一直没有升级，主要为
1. 设置了代理全部到https://xxx.yyy.com/ 下
2. 访问如 /h5-api/v1/detail，如果有配置mock就走mock，没有就走代理到https://xxx.yyy.com/h5-api/v1/detail

```js
const proxy = {
  _proxy: {
    proxy: {
      "/(.*)": "https://xxx.yyy.com/",
    },
    changeHost: true,
  },
  "GET /h5-api/v1/detail": { test: true },
```

——————————
我对比了一下2.0.4的代码，发现mock和proxy的顺序改了，说以话说现在还有其它的方案实现这种功能吗

![image](https://user-images.githubusercontent.com/14126445/99472116-ecc8c500-2982-11eb-805a-c9facc19de3f.png)

**Comment by jaywcjlove** [comment]
@aizigao https://github.com/jaywcjlove/mocker-api/issues/144#issuecomment-717007982

这个是配置顺序。你想要的顺序是什么什么顺序呢？

如果配置了 mocker 文件地址，就走 mocker 配置文件里面，如果没有就走传递的方法里面？

**Comment by aizigao** [comment]
@jaywcjlove 我想要的顺序是 就算配置了代理，如果已经有配置了对的mock 接口配置就走mock，没有配置的mock接口就走代理。
我们这边大部分接口还是想走真实的数据，部分接口走mock，这样会比较方便; 😄

**Comment by jaywcjlove** [comment]
mock 出来的数据不是假的数据？怎么是真实数据呢？

我们这边的需求是这样的，开发初期，都是 mock 出来的假数据，来了一个 API 配置一下代理走真实的，来了一个 API  再配置代理，走真实 API，

这样慢慢 mock 的数据就被替换掉了，不用去删除或者注释 mock 内容， 所以改了顺序。

@aizigao

**Comment by aizigao** [comment]
@jaywcjlove 比如我在开发一个内嵌web到某app的应用，如果不走真实接口，大概率oauth不过去，有些页面的权限比较多，每次都改mock文件比较麻烦，我写的了简单pr https://github.com/jaywcjlove/mocker-api/pull/152

**Comment by jaywcjlove** [comment]
你的意思是配置  proxy， mock 的API 自动失效？ @aizigao

**Comment by jaywcjlove** [comment]
@aizigao 这样不好吧，能不能弄个开关配置，既支持 proxy 优先，又支持 mock 优先？

**Comment by aizigao** [comment]
> 你的意思是配置 proxy， mock 的API 自动失效？ @aizigao

比如这个配置，
```
 _proxy: {
    proxy: {
      "/(.*)": "https://api.github.com/",
    },
    changeHost: true,
  },
  // 注释它则走 默认代理
  "GET /repos/jaywcjlove/mocker-api": {
    mock: true,
  },
```

我配置了 "GET /repos/jaywcjlove/mocker-api"，在访问其它github接口时可以直接到github,  访问 /repos/jaywcjlove/mocker-api时会走mock的数据，也就是使用mock时如果满足proxy条件也优先走mock

**Comment by aizigao** [comment]
> @aizigao 这样不好吧，能不能弄个开关配置，既支持 proxy 优先，又支持 mock 优先？

对，我是这个意思，那这个开关能不能整一个 👍

**Comment by cuidong626** [comment]
配置了拦截所有请求的代理后，就没办法走mock了，希望增加单独控制mock优先级的

**Comment by wll8** [comment]
> 配置了拦截所有请求的代理后，就没办法走mock了，希望增加单独控制mock优先级的

这个功能可以使用了吗？

**Comment by jaywcjlove** [comment]
@wll8 稍微等待，还没有时间开发

**Comment by urrri** [comment]
I also have the same problem.
I set mock for some requests and rest I want to pass through the proxy, but proxy today has higher priority and all my specific requests don't reach mock.

**Comment by jaywcjlove** [comment]
@aizigao  @chaosforfun  @urrri @wll8 @cuidong626  Upgrade `+ mocker-api@2.8.0`

https://github.com/jaywcjlove/mocker-api/blob/6d31d2017400d9658cfc2cf1b96662dcf94e6754/example/webpack/mocker/index.js#L7-L24

添加了个配置 `priority` 默认值为 `proxy`，要实现你们的想法，将参数设置为 `mocker`

- `proxy` 优先走代理配置
- `mocker` 优先 mock 配置
