### ISSUE TITLE
[Advice] Add issue template

### ISSUE THREAD

**Issue by vanpipy** [jaywcjlove/mocker-api#153]
Hi, @jaywcjlove ,

建议添加issue初始模板, 这样可以帮助使用的用户提供更有效的信息, 尤其是故障或者优化之类的情形.

**Comment by jaywcjlove** [comment]
@vanpipy 欢迎提交一个PR，目前我没有什么想法。

**Comment by vanpipy** [comment]
Hi, @jaywcjlove , 这个需要owner才能设置的 😃. 

* [How to create issue template](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository)

**Comment by jaywcjlove** [comment]
@vanpipy https://github.com/jaywcjlove/awesome-mac 这个 就是人家  PR 的，只需把对应的文件放入 `.github` 目录即可

**Comment by vanpipy** [comment]
Hi @jaywcjlove , there are two templates added - Bug report and feature request.

**Comment by jaywcjlove** [comment]
@vanpipy thx!
