### ISSUE TITLE
Types declaration files are not release package

### ISSUE THREAD

**Issue by huynguyentuong** [jaywcjlove/mocker-api#154]
In version **2.6.0**, the package structure is
```
mocker-api
|--lib
    |--bin
        |--index.js
        |--index.js.map
        |--index.d.ts    
```

However, for newer versions (from **2.7.0**), the structure has been changed to
```
mocker-api
|--lib
    |--bin
        |--mocker.js
        |--mocker.js.map
    |--src
        |--index.d.ts
```

Which cannot be understood by Typescript compiler. Adding the following configuration to ts.config.json helps but not very ideal.
```
{
    ...
     "include": [
         "node_modules/mocker-api/lib/src"
     ]
}
```

**Comment by jaywcjlove** [comment]
@huynguyentuong Thx! Upgrade `+ mocker-api@2.7.4`

**Comment by huynguyentuong** [comment]
Thanks for the super quick fix!
