### ISSUE TITLE
does it support Mock grammar?

### ISSUE THREAD

**Issue by HomyeeKing** [jaywcjlove/mocker-api#156]
Can we use Mock grammar in this?

**Comment by jaywcjlove** [comment]
@HomyeeKing I do not understand the meaning?

**Comment by HomyeeKing** [comment]
@jaywcjlove  额还是中文好了， 我试了试 里面不能用mock语法啊，目前不支持吗

**Comment by jaywcjlove** [comment]
mock语法 是什么语法？提供实例我看看 @HomyeeKing

**Comment by HomyeeKing** [comment]
@jaywcjlove  https://github.com/nuysoft/Mock/wiki/Getting-Started

**Comment by jaywcjlove** [comment]
@HomyeeKing 你使用这个库模拟数据返回就好了
