### ISSUE TITLE
啥时候支持Koa

### ISSUE THREAD

**Issue by coderyyx** [jaywcjlove/mocker-api#31]
啥时候支持Koa哦~

**Comment by jaywcjlove** [comment]
@coderyyx `webpack-api-mocker` 是 [`webpack-dev-server`](https://github.com/webpack/webpack-dev-server) 这个工具的扩展，`webpack-dev-server` 里面是 express 实现的，也就是说 `webpack-api-mocker ` 是 `express` 的一个中间件，所以已下子就可以支持 express。

此工具主要应用 webpack 应用中，暂时没有计划支持 Koa，如果你有想法可以提交 PR.

**Comment by jaywcjlove** [comment]
@coderyyx  了解。

**Comment by jaywcjlove** [comment]
@coderyyx 根据你的描述拥有了个新的灵感，通过命令来运行。

包变强大了之后将包名给改了： `webpack-api-mocker` => `mocker-api`

[Base example](https://github.com/jaywcjlove/webpack-api-mocker/tree/d86465ef299f92dcbb76d01ef62fd1620e8d32ab)
```bash
# Global install dependent.
npm install mocker-api -g
# Run server
mocker ./mocker/index.js
```

Or you can put it the `package.json` config as a current project dependency.

```diff
{
  "name": "base-example",
  "scripts": {
+    "api": "mocker ./mocker"
  },
  "devDependencies": {
+    "mocker-api": "^1.6.4"
  },
  "license": "MIT"
}
```

**Comment by coderyyx** [comment]
👍👍1、中间件的形式可以都支持Express和Koa，我这边写了个简单支持Koa的middleware；2、单独起一个mock服务器是可以的，我们原来是这样用的，后来觉得麻烦，就集成到项目里面去了，3、我觉得单独起mock服务也有优势的，项目更干净了，看个人喜好❤️~~
