### ISSUE TITLE
Feature: 能否支持一下vite配置呢？

### ISSUE THREAD

**Issue by ZDHSir** [jaywcjlove/mocker-api#319]
vite 怎么去使用？

**Comment by ZDHSir** [comment]
> vite 怎么去使用？

import { ProxyOptions } from "vite";

export const proxy:Record<string, string | ProxyOptions> | undefined = {
  "/xhr/(.*)":{
    target: 'xxxxx/api',
    // target: 'xxxxx',
    changeOrigin: true,
    rewrite(path){
      return path.replace(/^\/xhr/, '/')
    },
  }
};

**Comment by jaywcjlove** [comment]
@ZDHSir 不去支持 vite 是因为它有自己的插件， [`vite-plugin-mock-server`](https://www.npmjs.com/package/vite-plugin-mock-server)
