### ISSUE TITLE
是否可以增加 自動重新啟動的特性

### ISSUE THREAD

**Issue by imagine10255** [jaywcjlove/mocker-api#33]
Hi. 我使用下面這個方式來進行載入 mock 文件
能不能讓 更改 mock json 數據自動更新?

```
const delay = require('mocker-api/utils/delay');
const requireContext = require('require-context');

const db = requireContext('../../src/services/mock', true, /\.mock\.js$/);

// 延遲回應時間 (模擬 Loading 效果)
const delayTime = 1500;

function loadMockyFiles() {
    let mockProxy = {};
    db.keys().forEach(filename => {
        mockProxy = {...mockProxy, ...db(filename)};
    });
    return mockProxy;
}
const proxy = loadMockyFiles();
module.exports = delay(proxy, delayTime);
```

**Comment by imagine10255** [comment]
@jaywcjlove 我現在是用1.66, 還有更新版嗎?

因為我希望載入方式不用另外寫 import, 這樣會增加工作繁雜度

**Comment by jaywcjlove** [comment]
这个是最新的，你直接写JSON就不用引入任何其他内容。

> `因為我希望載入方式不用另外寫 require`  

这个我不太明白呢

**Comment by jaywcjlove** [comment]
@imagine10255 你是想做到，将不同 的API放到一个文件夹里面，让工具自动加载进来？

**Comment by imagine10255** [comment]
@jaywcjlove 我這邊的做法是參考 storybook 的載入方式

mock 接口 跟 json data 目錄結構

![image](https://user-images.githubusercontent.com/5771353/51086100-232ccc00-177d-11e9-99b8-830e146b0fe5.png)

進入點目錄位置與內容

![image](https://user-images.githubusercontent.com/5771353/51086116-3cce1380-177d-11e9-9930-2507444fb60d.png)

希望異動 json data 的時候, 可以不用重啟 mocker server

**Comment by jaywcjlove** [comment]
@imagine10255 我写了个 [loadData](https://github.com/jaywcjlove/mocker-api/tree/058a7f3d5ab68e20a99e8c25b9426b8dd49c01d4/example/loadData) 实例，你可以通过下面方式加载数据，我看你的代码数据应该是个 `JSON` 格式，你可以直接加载 JSON文件。

```js
const delay = require('mocker-api/utils/delay');

// 是否禁用代理
const noProxy = process.env.NO_PROXY === 'true';

function loadData(data) {
  const result = {};
  Object.keys(data).forEach((key) => {
    result[key] = require(data[key]);
  });
  return result;
}

const proxy = loadData({
  'GET /api/user': './db/user',
  'GET /api/user/info': './db/userInfo.json',
});

module.exports = (noProxy ? {} : delay(proxy, 1000));
```

https://github.com/jaywcjlove/mocker-api/blob/058a7f3d5ab68e20a99e8c25b9426b8dd49c01d4/example/loadData/mocker/index.js#L1-L19

如果你有简单的业务参考 [`db/user.js`](https://github.com/jaywcjlove/mocker-api/blob/058a7f3d5ab68e20a99e8c25b9426b8dd49c01d4/example/loadData/mocker/db/user.js)，可以在里面写一些简单的业务

```js
module.exports = (req, res) => {
  return res.json([
    {
      id: 1,
      username: 'kenny',
      sex: 34
    }, {
      id: 2,
      username: 'mocker',
      sex: 23
    }
  ]);
}
```

**Comment by jaywcjlove** [comment]
@imagine10255 如果你是返回 `json` 你就可以写 `json` 文件就可以了，实例：[userInfo.json](https://github.com/jaywcjlove/mocker-api/blob/058a7f3d5ab68e20a99e8c25b9426b8dd49c01d4/example/loadData/mocker/db/userInfo.json)

这样可以热加载不用重新启动

**Comment by Sliect** [comment]
![image](https://user-images.githubusercontent.com/26275750/60427635-abb70000-9c29-11e9-8d7e-2d1afb23ec47.png)
@jaywcjlove 我这样写无法监听到引用文件的改变，有没有什么好的解决办法呢

**Comment by Sliect** [comment]
对了，我是用vue-cli3搭建的

**Comment by buyixiaojiang** [comment]
一是可以把下面的代码移动到 `../../src/services/mock`目录下，此目录下的代码会被监听到。

```
const delay = require('mocker-api/utils/delay');
const requireContext = require('require-context');

const db = requireContext('../../src/services/mock', true, /\.mock\.js$/);

// 延遲回應時間 (模擬 Loading 效果)
const delayTime = 1500;

function loadMockyFiles() {
    let mockProxy = {};
    db.keys().forEach(filename => {
        mockProxy = {...mockProxy, ...db(filename)};
    });
    return mockProxy;
}
const proxy = loadMockyFiles();
module.exports = delay(proxy, delayTime);
```
或者说新增加个配置项，去监听配置项目录里面的代码

**Comment by jaywcjlove** [comment]
可以使用 [`nodemon`](https://www.npmjs.com/package/nodemon) 单独起一个 mock 服务

**Comment by jaywcjlove** [comment]
经过我一顿猛如虎的测试，自动热加载，好像新的版本解决了这个问题。

测试版本 [`mocker-api@1.7.9`](https://www.npmjs.com/package/mocker-api)
