### ISSUE TITLE
Bug: Merge dependency update for path-to-regexp to resolve vulnerability

### ISSUE THREAD

**Issue by Fryerstarter** [jaywcjlove/mocker-api#331]
Hey there! I see this project has not been active in a few months now. Any chance you can get a release out with this upgrade for path-to-regexp to resolve the associated security vuln? https://github.com/jaywcjlove/mocker-api/pull/330
Thanks!

**Comment by jaywcjlove** [comment]
@Fryerstarter thx!

**Comment by Fryerstarter** [comment]
Thanks for the quick turnaround!
