### ISSUE TITLE
没有支持 cors吗

### ISSUE THREAD

**Issue by chaosforfun** [jaywcjlove/mocker-api#34]
用get请求可以,用post请求时报options方法请求 404

![image](https://user-images.githubusercontent.com/2226267/53164635-a0b0eb00-360b-11e9-94c1-149f8defaaf1.png)

![image](https://user-images.githubusercontent.com/2226267/53164618-9262cf00-360b-11e9-9a30-56a09d42e85e.png)

**Comment by jaywcjlove** [comment]
@chaosforfun 我经过测试没有任何问题，你可以运行实例看看。[options request method test case.](https://github.com/jaywcjlove/mocker-api/tree/61915a86bad0a7d76fe93fcd964c872d3befe2ab/example/loadData)

你可以提供一个 demo 我看看？或者升级最新版本？

![image](https://user-images.githubusercontent.com/1680273/53165096-cc80a080-360c-11e9-9564-38918504764f.png)

**Comment by chaosforfun** [comment]
我看了demo,里面直接写了 "OPTIONS xxxx",我希望不需要写 OPTIONS, 只写一个 "POST xxxx" 就可以了.

**Comment by jaywcjlove** [comment]
@chaosforfun 这是我只有一个 `'POST /api/login/account'` 一样没有问题我不知道你怎么发送请求的。

```js
const delay = require('mocker-api/utils/delay');

// 是否禁用代理
const noProxy = process.env.NO_PROXY === 'true';

const proxy = {
  'POST /api/login/account': (req, res) => {
    const { password, username } = req.body;
    if (password === '888888' && username === 'admin') {
      return res.json({
        status: 'ok',
        code: 0,
        token: "sdfsdfsdfdsf",
        data: {
          id: 1,
          username: 'kenny',
          sex: 6
        }
      });
    } else {
      return res.json({
        status: 'error',
        code: 403
      });
    }
  },
}
module.exports = (noProxy ? {} : delay(proxy, 1000));
```

![image](https://user-images.githubusercontent.com/1680273/53216840-dc41c880-3690-11e9-8349-ae60e23ab87d.png)

**Comment by chaosforfun** [comment]
请您在浏览器里(要跨域)测一下吧,因为CORS是浏览器的限制,用其curl 或 postman应该是不会有问题的.

**Comment by jaywcjlove** [comment]
@chaosforfun 我不知道你是怎么使用的

![image](https://user-images.githubusercontent.com/1680273/53220907-e3bd9d80-36a1-11e9-8ace-c420677d2c4b.png)

**Comment by chaosforfun** [comment]
我建了个demo,你看下吧,https://github.com/chaosforfun/demo
不好意思我以为能说清楚呢,应该早点上代码的.
![image](https://user-images.githubusercontent.com/2226267/53235413-b508ec80-36cc-11e9-9b5b-4219efeee3dd.png)

**Comment by jaywcjlove** [comment]
@chaosforfun https://github.com/chaosforfun/demo/pull/1

**Comment by chaosforfun** [comment]
两个问题.:
1 不应该去掉 content-type,去掉后就不是正确的post请求了,content-type就变成 text/plain了.
从去掉content-type就可以了这个现象来看应该是代码里少处理了一些情况.
2 我看文档里说了可以不依赖 webpack了,我才这样玩的.
