### ISSUE TITLE
入参可否兼容 require ?

### ISSUE THREAD

**Issue by jian263994241** [jaywcjlove/mocker-api#35]
可否兼容 require module 入参 ?

devServer: {
  ...
  before(app){
    apiMocker(app, require('./mocker/index.js'), {
      proxy: {
        '/repos/*': 'https://api.github.com/',
        '/:owner/:repo/raw/:ref/*': 'http://127.0.0.1:2018'
      },
      changeHost: true,
    })
  }
},

**Comment by jaywcjlove** [comment]
@jian263994241 不支持。支持下面这种方式。

```js
apiMocker(app, require.resolve('./mocker/index'))
```
