### ISSUE TITLE
能将线上的请求拦截吗

### ISSUE THREAD

**Issue by IEfucker** [jaywcjlove/mocker-api#36]
对于本地的请求能拦截，返回mock数据
对于线上地址，比如http://www.baidu.com/api/xxx/test
这样的接口不能使用mock代理吗

**Comment by jaywcjlove** [comment]
@IEfucker 你可能对代理有误解。

**Comment by IEfucker** [comment]
@jaywcjlove 啊，那我这样做不行喽？

**Comment by jaywcjlove** [comment]
@IEfucker 可以的，你可以运行下面这个[例子](https://github.com/jaywcjlove/mocker-api/tree/d86465ef299f92dcbb76d01ef62fd1620e8d32ab/example/webpack)。试一试。

https://github.com/jaywcjlove/mocker-api/blob/d86465ef299f92dcbb76d01ef62fd1620e8d32ab/example/webpack/mocker/index.js#L9-L14

**Comment by IEfucker** [comment]
抱歉我好像没有把我的问题表述清楚
我遇到一个问题，请求的接口用localhost(当然这个接口在本地也是通过代理，代理到真实地址)可以使用mock拦截，返回mock数据
但我使用真是接口 http://www.baidu.com/api/xxx/test 这种，为什么mock拦截不到

**Comment by jaywcjlove** [comment]
@IEfucker 你对代理可能有误解，你直接访问API `http://www.baidu.com/api/xxx/test` 浏览器直接访问百度API，没有走你本地服务，`mocker-api` 不是一个浏览器插件，它是你本地服务的中间件。

**Comment by IEfucker** [comment]
哦傻逼了
