### ISSUE TITLE
npm pulish 一下吧，想用下新功能

### ISSUE THREAD

**Issue by hfuuss** [jaywcjlove/mocker-api#39]
npm pulish 一下吧，想用下新功能

**Comment by hfuuss** [comment]
![image](https://user-images.githubusercontent.com/14094844/56207362-1e7bfa80-6081-11e9-9773-729b31f00cc6.png)

**Comment by jaywcjlove** [comment]
@hfuuss [mocker-api](https://www.npmjs.com/package/mocker-api)
