### ISSUE TITLE
Watch polling

### ISSUE THREAD

**Issue by Aliaksandr-Padabed** [jaywcjlove/mocker-api#44]
If served from devvm can't detect changes. Polling could solve this.` chokidar` has config property `usePolling`,

**Comment by jaywcjlove** [comment]
@Aliaksandr-Padabed thx!

**Comment by jaywcjlove** [comment]
[Chokidar](https://www.npmjs.com/package/chokidar), This package?

**Comment by Aliaksandr-Padabed** [comment]
yes

**Comment by jaywcjlove** [comment]
@Aliaksandr-Padabed thx!
