### ISSUE TITLE
Can mocker-api be used in Express and webpack-dev-middleware?

### ISSUE THREAD

**Issue by cag2050** [jaywcjlove/mocker-api#47]
Can mocker-api be used in Express and webpack-dev-middleware?

**Comment by jaywcjlove** [comment]
@cag2050 Can be used together.

**Comment by cag2050** [comment]
> @cag2050 Can be used together.

I see. I can use Express with webpack-dev-middleware.
Thanks.

**Comment by cag2050** [comment]
> @cag2050 Can be used together.

Do you have demo that use Express with webpack-dev-middleware ？

**Comment by cag2050** [comment]
The demo using Express with webpack-dev-middleware, website: https://github.com/cag2050/element_demo#%E4%BD%BF%E7%94%A8%E7%BD%91%E5%9D%80httplocalhost9098axios-%E6%B5%8B%E8%AF%95mocker-api-%E7%9A%84%E4%BD%BF%E7%94%A8%E6%AD%A5%E9%AA%A4

**Comment by jaywcjlove** [comment]
@cag2050 Learn about `host`.  `sudo vi /etc/hosts` .
