### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by arloduff** [jaywcjlove/mocker-api#51]
# The problem
The error `TypeError: Cannot read property 'replace' of undefined` is thrown when `contentType` is undefined. Seems to be caused by https://github.com/jaywcjlove/mocker-api/commit/49358ca5d59ce9a08488d746d2a5995d9b451417

This is problematic for users such as myself, who use Axios, which deliberately strips out a `Content-Type` header from any request which is not sending data, even if one is provided. See https://github.com/axios/axios/issues/86

# Steps to reproduce

Send a request to your mock-api which does not have a `Content-Type` header. Using Axios, you can send something similar to:

    this.axios.get(url), {
      headers: {
        'Content-Type': 'application/json',
        Accept: 'application/json'
      },
      params: {
        // Your parameters here
      }
    }).then(result => result.data)

Mocker-api will fail with the error `TypeError: Cannot read property 'replace' of undefined` because `contentType` will come out as undefined, even though it was provided.

I understand you may argue that Axios should not be stripping out the Content-Type from the request; however, it's still a good practice for this codebase to check for one before calling `replace` on a variable which may be undefined.

**Comment by jaywcjlove** [comment]
@arloduff Upgrade `+ mocker-api@1.7.9`

**Comment by arloduff** [comment]
Thanks @jaywcjlove !
