### ISSUE TITLE
建议把配置和MOCK 拆分开来

### ISSUE THREAD

**Issue by scarcoco** [jaywcjlove/mocker-api#66]
1. 配置`_proxy` 和 接口MOCK 是否应该拆分开来？
2. chokidar 的配置是否可以支持传入？
3. 目前看 watch 了整个目录，但是获取 mock 数据 还是单纯重传入的 watchFile 获取，没有而不是 watch 的文件自动导入，比如在watchFile 中引入其他文件？

**Comment by jaywcjlove** [comment]
@scarcoco 

1. `_proxy ` 是可以删除通过 `options` 传入的 `apiMocker(app, mocker[,options])`
2. `chokidar` 只是使用了 `watch` 方法，可以传入 `watch` 的 `options`
3. `watchFile`, 是入口文件，会自动监听入口文件所在的目录。

**Comment by jaywcjlove** [comment]
@scarcoco `Upgrade mocker-api@1.13.0`

**Comment by scarcoco** [comment]
@jaywcjlove 第三点 既然都 `watch` 目录下所有文件，按照现在方式还需要在入口引入才能 `mock`

**Comment by scarcoco** [comment]
> @scarcoco `Upgrade mocker-api@1.13.0`

好的。

**Comment by jaywcjlove** [comment]
@scarcoco 最早的版本只是引入一个文件，监听一个文件，后面大家提需求分离一个文件，便于维护。这样一直维护下来，通过一个入口文件，获取该文件的目录路径，让该文件目录下面的所有文件监听实时更改。

**Comment by scarcoco** [comment]
> @scarcoco 最早的版本只是引入一个文件，监听一个文件，后面大家提需求分离一个文件，便于维护。这样一直维护下来，通过一个入口文件，获取该文件的目录路径，让该文件目录下面的所有文件监听实时更改。

分离是必须的，这种情况应该传入目录，而不是由文件到目录？现在是 `watch` 和 `mock` 范围不一致，`watch` 整个目录，如果不从入口引入，实际是没有 `mock`。

其实最简单是就是 `mock` 目录下所有文件， `exclude` 的除外。

**Comment by jaywcjlove** [comment]
@scarcoco 之前考虑过 `mock` 目录下所有文件这样会比较容易一些，但是已经添加了很多功能，比如配置中 `_proxy` 功能就废了。

**Comment by scarcoco** [comment]
> @scarcoco 之前考虑过 `mock` 目录下所有文件这样会比较容易一些，但是已经添加了很多功能，比如配置中 `_proxy` 功能就废了。

嗯，这个后续重构可以考虑一下，先关了吧。
