### ISSUE TITLE
可以监听mock文件新增吗

### ISSUE THREAD

**Issue by zhangshihuann** [jaywcjlove/mocker-api#82]
试了下可以加载/mock/* 下的文件了，也可以监听到文件的修改
但是在项目起来之后去新增mock文件就监听不到了，这个可以支持一下吗
或者第2个参数支持传目录？比如 /mock/ 这样，监听文件变动？
apiMocker(app, mockerFile, options)

**Comment by jaywcjlove** [comment]
@zhangshihuann 多个入口文件配置需要重启。不过 入口文件引入的文件，是可以监听到的。好像入口文件需要保存一下的。
