### ISSUE TITLE
Axios 无法拦截mocker-api请求

### ISSUE THREAD

**Issue by gapkukb** [jaywcjlove/mocker-api#88]
Axios.interceptors.request.use(config => {
    console.log(config);
    return config
})

代码如上，经测试。只有通过 mocker-api 代理转发的请求可以被拦截打印处配置
未经过代理直接访问 mocker-api 数据的请求，无法被拦截。
请问是我疏忽了mocker-api 的哪个配置吗

**Comment by jaywcjlove** [comment]
@gapkukb 可有实例我看看？

**Comment by gapkukb** [comment]
是我的问题。感谢回复
