### ISSUE TITLE
如何指定端口

### ISSUE THREAD

**Issue by baisijian** [jaywcjlove/mocker-api#89]
如何指定端口

**Comment by jaywcjlove** [comment]
@baisijian 什么意思，是启动服务还是代理端口？

**Comment by baisijian** [comment]
@jaywcjlove  mocker ./mocker/index.js **--port 8080** ?

**Comment by jaywcjlove** [comment]
@baisijian 端口指定是通过环境变量 `PORT`

https://github.com/jaywcjlove/mocker-api/blob/ba71e6de5593c349fd7a7174dbe084ddb8cd64cb/src/bin/mocker.ts#L20

**Comment by jaywcjlove** [comment]
```bash
  mocker mock/index.js
  mocker mock/index.js --port 7788
  mocker mock/index.js --host 0.0.0.0
  mocker mock/m1.js test/m2.js
  mocker mock/m1.js --config mocker.config.json
```

现在更强大了一点，不单通过环境变量，配置都可以指定端口，升级到 `mocker-api@2.7.0`

#144
